# Site settings
title: Per aspera ad astra
description: Coming soon...
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: fremorie.github.io
user_description: ML enthusiast 
user_title: 
email: anon@anon.com
github_username:  fremorie

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
