# Site settings
title: Coming soon...
description: To ask the right question is harder than to answer it.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "fremorie.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: fremorie
user_description: ML enthusiast 
user_title: 
email: anon@anon.com
twitter_username:
github_username: fremorie
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
